### ISSUE TITLE
Milestone of bugs to fix until "real" release

### ISSUE THREAD

**Issue by GuntherDW** [GuntherDW/Applied-Energistics-2#1]
List of bugs still to squash :
I will edit this list whenever I find new bugs in my survival playthrough.

- [ ] Hoppers inserting items into the inscriber even when told not to. Thanks @fscan bdf46a6ee2b503cf690a68a93b0619bce1076467
- [x] Rendering bug on cables and select blocks like the crafting processors on a specific side. 178198b0c6581d0cf90a848e4920a2064e6cab2c
- [x] Showing "Air" tooltip in the interface terminal where it shouldn't. b819fe4adbbcbeb3389677fbb096ddf8ba7307c7
- [x] Facade recipes for pretty much every item where they should only exist for blocks. 61b81fc802a3fc1839cb57bfa25e40848147984a
- [x] Pattern terminal doesn't consume blank pattern when setting recipe. 0be201164598c3a4cc9e5a961f11e0ca80a7e975
- [x] Exception thrown when in survival and used last "part" of a stack. bce500616cd6b74b12449e2f34f2ec7f3981904a

**Comment by fscan** [comment]
regarding the hopper thing, maybe take a look at my pull request for the upstream repo:
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2933

**Comment by GuntherDW** [comment]
@fscan That pull req indeed fixes the issue. It needs a 1.11 "isEmpty()" check instead of " != null".
If you can add that as a pull request to this repo I'll be able to correctly credit you. (instead of just taking your code and pushing it, with a note in the commit message).

**Comment by fscan** [comment]
Just copy it, i'm don't have the time to handle the merge conflicts for the rebase atm :)

**Comment by GuntherDW** [comment]
As promised, https://github.com/GuntherDW/Applied-Energistics-2/releases/tag/rv5.alpha.0
I'll still continue to fix bugs, but I think it's far enough along for others to kind of play around.

Don't put this in worlds that you want to play in long term though. Things might still change that could corrupt or clear your AE stuff.
